name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Secret injection
        run: |
          cat <<EOF > .env
          REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_RECONNECT_PERIOD=${{ secrets.REACT_APP_RECONNECT_PERIOD }}
          REACT_APP_CONNECTION=${{ secrets.REACT_APP_CONNECTION }}
          EOF

      - name: Deploy Application
        run: |
          docker-compose --env-file .env -f docker-compose.yaml up -d --build
